name: Release By Tags

on:
  workflow_call:
    inputs:
      tag_list:
        required: true
        type: string
      project:
        required: false
        type: string
  workflow_dispatch:
    inputs:
      tag_list:
        description: 'Release specified tags:'
        required: true

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Build All
      uses: ./.github/workflows/build_all
      with:
        project: ${{ inputs.project }}

    - name: Need for Speed Undercover Generic Fix
      uses: ./.github/workflows/release_tag
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag_list: ${{ format('{0},{1}', github.event.inputs.tag_list, inputs.tag_list) }}
        tag: nfsuc
        artifacts: data/Archives/NFSUndercover.GenericFix.zip

    - name: Need for Speed ProStreet Generic Fix
      uses: ./.github/workflows/release_tag
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag_list: ${{ format('{0},{1}', github.event.inputs.tag_list, inputs.tag_list) }}
        tag: nfsps
        artifacts: data/Archives/NFSProStreet.GenericFix.zip

    - name: Need For Speed Underground Widescreen Fix
      uses: ./.github/workflows/release_tag
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag_list: ${{ format('{0},{1}', github.event.inputs.tag_list, inputs.tag_list) }}
        tag: nfsu
        artifacts: data/Archives/NFSUnderground.WidescreenFix.zip

    - name: Need For Speed Underground 2 Widescreen Fix
      uses: ./.github/workflows/release_tag
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag_list: ${{ format('{0},{1}', github.event.inputs.tag_list, inputs.tag_list) }}
        tag: nfsu2
        artifacts: data/Archives/NFSUnderground2.WidescreenFix.zip

    - name: Need For Speed Most Wanted (2005) Widescreen Fix
      uses: ./.github/workflows/release_tag
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag_list: ${{ format('{0},{1}', github.event.inputs.tag_list, inputs.tag_list) }}
        tag: nfsmw
        artifacts: data/Archives/NFSMostWanted.WidescreenFix.zip

    - name: Need For Speed Carbon Widescreen Fix
      uses: ./.github/workflows/release_tag
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag_list: ${{ format('{0},{1}', github.event.inputs.tag_list, inputs.tag_list) }}
        tag: nfsc
        artifacts: data/Archives/NFSCarbon.WidescreenFix.zip

    - name: Xbox Rain Droplets Plugins
      uses: ./.github/workflows/release_tag
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag_list: ${{ format('{0},{1}', github.event.inputs.tag_list, inputs.tag_list) }}
        tag: xrd
        artifacts: data/Archives/PPSSPP.XboxRainDroplets.zip, data/Archives/PCSX2F.XboxRainDroplets.zip
