name: Release By Tag

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: The tag of the release
        required: true
        type: choice
        options:
        - nfsc
        - nfsmw
        - nfsps
        - nfsu
        - nfsu2
        - nfsuc 

env:
  nfsc: "/t:Win32\\NeedForSpeed\\NFSCarbon_WidescreenFix"
  nfsmw: "/t:Win32\\NeedForSpeed\\NFSMostWanted_WidescreenFix"
  nfsps: "/t:Win32\\NeedForSpeed\\NFSProStreet_GenericFix"
  nfsu: "/t:Win32\\NeedForSpeed\\NFSUnderground_WidescreenFix"
  nfsu2: "/t:Win32\\NeedForSpeed\\NFSUnderground2_WidescreenFix"
  nfsuc: "/t:Win32\\NeedForSpeed\\NFSUndercover_GenericFix"
  xrd: "/t:PPSSPP\\PPSSPP_XboxRainDroplets /t:PCSX2F\\PCSX2F_XboxRainDroplets"

jobs:
  setup_project_name:
    runs-on: ubuntu-latest
    outputs:
      project_name: ${{ steps.prj_name.outputs.project_name }}
    steps:
      - name: Print inputs passed to the reusable workflow
        id: prj_name
        run: |
          echo "project_name=${{ env[inputs.tag_name] }}" >> $GITHUB_OUTPUT
  call-workflow-passing-data:
    needs: setup_project_name
    uses: ThirteenAG/WidescreenFixesPack/.github/workflows/all.yml@master
    with:
      tag_list: ${{ inputs.tag_name }}
      project: ${{ needs.setup_project_name.outputs.project_name }}
